--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-prod
  region: eu-west-1

vpc:
  id: "vpc-014a907fc534abaa5"
  subnets:
    private:
      eu-west-1a:
        id: "subnet-0e26a26c10"
      eu-west-1b:
        id: "subnet-00697134"
      eu-west-1c:
        id: "subnet-068c4a0"

nodeGroups:
  - name: eks-nodes
    instanceType: r4.xlarge
    ssh:
      publicKeyName: prod-apps
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-13: "owned"
    desiredCapacity: 4
    minSize: 4
    maxSize: 4
    privateNetworking: true
    availabilityZones: ["eu-west-1a","eu-west-1b","eu-west-1c"]
    labels:
      nodegroup: prod
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
